apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  SAST_Scan:
    steps:
      - uses: cloudbees-io/findsecbugs-sast-scan-code@v1
        name: SAST Scan
        kind: scan
        with:
          language: LANGUAGE_PYTHON
